#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run PHPStan to analyze code
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "PHPStan pegou algo de errado! Ajeite para continuar... 😉";
    exit 1;
fi;

# Run Pest tests
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Opss! Algo deu errado nos testes... 😢";
    exit 1;
fi;

# Format each changed file using Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;
